### ISSUE TITLE
♻️ refactor: p2; sending an API request every time a space is selected

### ISSUE THREAD

**Issue by forest-im** [jaam-toast/jaam-toast-frontend#28]
## Issue

- p2; sending an API request every time a space is selected

## Description

- new 페이지에서 space 선택할 때마다 repository를 가져오는 api를 실행함
- 선택한 repository를 state에 저장할 수 있으면 api 요청을 줄일 수 있을 것 같음

**Comment by 0jaaack** [comment]
```typescript
function BuildOptionRepoList({
  space, // 1. space를 prop으로 전달받음
  searchWord,
  onOptionClick,
}: BuildOptionRepoListProps) {
  const { user } = useUser();
  const { data } = useQuery({
    queryKey: ["new-repo-select-page", space, "repos"], // 2. queryKey에 space 삽입해서 caching
    queryFn: (생략)
  });
```

react-query의 캐싱으로 해결할 수 있을 듯 합니다.
space가 선택될 때 space의 repository를 가져오는 로직은 `BuildOptionRepoList`에서 수행하는데,
react-query의 queryKey로 space를 넣어주어 캐싱이 이루어지도록 할 수 있습니다.

현재 코드에서는 반영되어있지 않은데, 추후 반영하겠습니다..

**Comment by ponjaehyeok** [comment]
> ```ts
> function BuildOptionRepoList({
>   space, // 1. space를 prop으로 전달받음
>   searchWord,
>   onOptionClick,
> }: BuildOptionRepoListProps) {
>   const { user } = useUser();
>   const { data } = useQuery({
>     queryKey: ["new-repo-select-page", space, "repos"], // 2. queryKey에 space 삽입해서 caching
>     queryFn: (생략)
>   });
> ```
> 
> react-query의 캐싱으로 해결할 수 있을 듯 합니다. space가 선택될 때 space의 repository를 가져오는 로직은 `BuildOptionRepoList`에서 수행하는데, react-query의 query�Key로 space를 넣어주어 캐싱이 이루어지도록 할 수 있습니다.
> 
> 현재 코드에서는 반영되어있지 않은데, 추후 반영하겠습니다..

**Comment by 0jaaack** [comment]
반영될 PR이 merget되면 close하겠습니다.
