### ISSUE TITLE
♻️ refactor: p3; no default settings when entering a new page

### ISSUE THREAD

**Issue by forest-im** [jaam-toast/jaam-toast-frontend#30]
## Issue

- p3; no default settings when entering a new page

## Description

- new 페이지로 들어갔을 때 기본값 셋팅이 되어있지 않음
  - mui Select 태그의 `rendervalue={() => value}`를 이용하면 적용할 수 있지만 recoil state 변경 필요
  - state 변경 필요한 이유: 현재 select의 value값을 url값으로 쓰고 있어 동적으로 적용하기 힘듦. (url 값은 선택한 이름이 organization인지 user인지 구분하는 용도로만 사용하고 있음 - `gitNamespaceList `배열의 첫 번째 값이 user 값이기 때문에 `gitNamespaceList`로 org인지 user인지 판단 가능)

**Comment by 0jaaack** [comment]
이슈 삭제
